version: 2
jobs:
  unitTests:
    docker:
      - image: circleci/php:7.2.8-apache-node-browsers
    steps:
      - checkout
      - run: composer install --dev
      - run: ./vendor/bin/phpunit -c phpunit.xml
workflows:
  version: 2
  tests:
    jobs:
      - unitTests
